#!/bin/bash

curl -Lo manifest-tool https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-amd64
chmod +x manifest-tool

./manifest-tool push from-args \
    --platforms linux/amd64,linux/arm/v6,linux/arm/v7 \
    --template ${DOCKER_REPO}:${SOURCE_BRANCH}-ARCHVARIANT \
    --target ${DOCKER_REPO}:${SOURCE_BRANCH} \
    --ignore-missing
